server:
  port: 8088
  ssl:
    enabled: false

spring:
  kafka:
    bootstrap-servers: localhost:9092
  r2dbc:
    pool:
      enabled: false

service:
  weather:
    uri: http://localhost:8080/weather-API
  overpass:
    uri: https://overpass-api.de/api/interpreter