server:
  port: 8082
  ssl:
    enabled: false

spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 10
      hash:
        key: app_user
  r2dbc:
    url: r2dbc:postgresql://localhost:5427/postgresDB
    username: userok
    password: password