server:
  port: 8089

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5427/SunnySideBotDataBase
    username: maksym
    password: maks09172239

service:
  weather:
    uri: http://localhost:8080/weather-API
  activation:
    uri: http://localhost:8087/user/activation?id=